version: '2.0'
services:
  # redis:
  #   image: redis:5.0.5
  #   container_name: trycatch-redis-container
  #   restart: always
  #   volumes:
  #     - ./redis.conf:/usr/local/etc/redis/redis.conf
  #   networks:
  #     - "trycatch_net"
  #   ports:
  #     - "6666:6379"

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3333:3306"
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./db/data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 342531

  # server:
  #   container_name: trycatch-server-container
  #   restart: always
  #   volumes:
  #     - ./server/:/home/trycatch/server/
  #   ports:
  #     - "7001:7001"
  #     - "9223:9223"
  #   environment:
  #     WAIT_HOSTS: db:3306
  #     WAIT_HOSTS: redis:6379
  #   depends_on:
  #     - db
  #     - redis
  #   networks:
  #     - "trycatch_net"
  #   build:
  #     context: server
  
    
  # web:
  #   container_name: trycatch-web-container
  #   image: nginx
  #   networks:
  #     - "trycatch_net"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/trycatch.conf
  #     - ./web/build/:/home/trycatch/web/
  #   ports:
  #     - "8060:8080"

# networks:
#   trycatch_net:
#     driver: bridge
