export const DEFAULT_ROLE_CODE = {
  ROOT: 'ROOT',
  ADMIN: 'ADMIN',
  USER: 'USER',
  PROJECT_ADMIN: 'PROJECT_ADMIN',
  PROJECT_MEMBER: 'PROJECT_MEMBER'
};

export const PERMISSION_CODE = {
  ANALYSE_EVENT: 'ANALYSE_EVENT',
  ANALYSE_FUNNEL: 'ANALYSE_FUNNEL',
  ANALYSE_PATH: 'ANALYSE_PATH',

  ANALYSE_CUSTOM: 'ANALYSE_CUSTOM',

  BOARD_SEARCH: 'BOARD_SEARCH',
  BOARD_DEL: 'BOARD_DEL',
  BOARD_ADD: 'BOARD_ADD',
  BOARD_UPDATE: 'BOARD_UPDATE',
  BOARD_INFO: 'BOARD_INFO',

  METADATA_SEARCH: 'METADATA_SEARCH',
  METADATA_ADD: 'METADATA_ADD',
  METADATA_DEL: 'METADATA_DEL',
  METADATA_UPDATE: 'METADATA_UPDATE',
  METADATA_ENABLE: 'METADATA_ENABLE',
  METADATA_DISABLE: 'METADATA_DISABLE',

  PERMISSION_SEARCH: 'PERMISSION_SEARCH',
  PERMISSION_ADD: 'PERMISSION_ADD',
  PERMISSION_DEL: 'PERMISSION_DEL',
  PERMISSION_UPDATE: 'PERMISSION_UPDATE',

  PROJECT_SEARCH_ALL: 'PROJECT_SEARCH_ALL',
  PROJECT_SEARCH: 'PROJECT_SEARCH',
  PROJECT_ADD: 'PROJECT_ADD',
  PROJECT_DEL: 'PROJECT_DEL',
  PROJECT_UPDATE: 'PROJECT_UPDATE',
  PROJECT_INFO: 'PROJECT_INFO',
  PROJECT_MEMBER_ADD: 'PROJECT_MEMBER_ADD',
  PROJECT_MEMBER_DEL: 'PROJECT_MEMBER_DEL',
  PROJECT_MEMBER_UPDATE: 'PROJECT_MEMBER_UPDATE',

  REPORT_SEARCH: 'REPORT_SEARCH',
  REPORT_ADD: 'REPORT_ADD',
  REPORT_DEL: 'REPORT_DEL',
  REPORT_UPDATE: 'REPORT_UPDATE',
  REPORT_INFO: 'REPORT_INFO',

  ROLE_SEARCH: 'ROLE_SEARCH',
  ROLE_ADD: 'ROLE_ADD',
  ROLE_DEL: 'ROLE_DEL',
  ROLE_UPDATE: 'ROLE_UPDATE',

  TEAM_SEARCH: 'TEAM_SEARCH',
  TEAM_ADD: 'TEAM_ADD',
  TEAM_DEL: 'TEAM_DEL',
  TEAM_UPDATE: 'TEAM_UPDATE',
  TEAM_INFO: 'TEAM_INFO',

  USER_SEARCH: 'USER_SEARCH',
  USER_ADD: 'USER_ADD',
  USER_DEL: 'USER_DEL',
  USER_UPDATE: 'USER_UPDATE',

  SEARCH_USER_TIMELINE: 'SEARCH_USER_TIMELINE'
};
